{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hal-nemofinder.fullname" . }}-api
  labels:
    {{- include "hal-nemofinder.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if .Values.api.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  {{- else if .Values.api.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hal-nemofinder.api.selectorLabels" . | nindent 6 }}
{{- end }}
